	echo  "\e[31m \t\t\t\t\t-BBBBBBBB     BB      BB  BBBBBBBBBB-\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB  BB      BB  BB        -\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB  BB      BB  BB        -\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB  BB      BB  BB        -    .--.\e[0m"
	echo  "\e[31m \t\t\t\t\t-BBBBBBBB     BB      BB  BBBBBBBB  -   |o_o |\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB    BB  BB    BB        -   |:_/ |\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB      BB      BB        -  //   \ \'\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB      BB      BB        - (| JGP | )'\e[0m"
	echo  "\e[31m \t\t\t\t\t-BB       BB      BB      BB        -/'\_   _/'\'\e[0m"
	echo  "\e[31m \t\t\t\t\t-BBBBBBBBB        BB      BBBBBBBBBB-\___)=(___/'\e[0m"	